(ns secret-santa-web.handler
    (:require [compojure.core :refer :all]
      [compojure.route :as route]
      [compojure.handler :refer [site]]
      [ring.middleware.resource :refer [wrap-resource]]
      [ring.middleware.json :refer [wrap-json-response wrap-json-body]]
      [ring.middleware.content-type :refer [wrap-content-type]]
      [ring.middleware.not-modified :refer [wrap-not-modified]]
      [ring.middleware.defaults :refer [wrap-defaults site-defaults]]
      [ring.middleware.cookies :refer [wrap-cookies]]
      [ring.util.response :refer [resource-response content-type]]
      [ring.adapter.jetty :as jetty]
      [environ.core :refer [env]]
      [secret-santa-web.models.migrations :refer [migrate]]
      [postal.core :refer [send-message]]
      [clojure.java.jdbc :as sql]
      [clj-time.core :as t]
      [clj-time.format :as f]
      [clj-time.coerce :as c]
      [clj-time.local :as l]
      [clj-time.jdbc]))